spring:
  application:
    name: gateway

  cloud:
    gateway:
      mvc:
        routes:
        - id: jokes
          uri: http://jokeservice:8082/
          predicates:
            - Path=/api/jokes/**
          filters:
            - RewritePath=/api/jokes/?(?<segment>.*), /$\{segment}
        - id: quotes
          uri: http://quoteservice:8083/
          predicates:
            - Path=/api/quotes/**
          filters:
            - RewritePath=/api/quotes/?(?<segment>.*), /$\{segment}
        - id: resource
          uri: http://resourceserver:8080/
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}