spring:
  application:
    name: gateway

  cloud:
    gateway:
      mvc:
        routes:
        - id: jokes
          uri: http://resourceserver:8080/
          predicates:
            - Path=/api/**
          filters:
                - RewritePath=/api/?(?<segment>.*), /$\{segment}